export const wordList = [
  { id: 1, word: "abundant", meaning: "풍부한", example: "The region has abundant natural resources.", level: "intermediate" },
  { id: 2, word: "benevolent", meaning: "자비로운, 친절한", example: "She was a benevolent leader who cared for her people.", level: "advanced" },
  { id: 3, word: "cautious", meaning: "조심스러운", example: "Be cautious when crossing the road.", level: "beginner" },
  { id: 4, word: "diligent", meaning: "부지런한", example: "He is a diligent student who always does his homework.", level: "intermediate" },
  { id: 5, word: "eloquent", meaning: "유창한, 설득력 있는", example: "Her eloquent speech moved the audience.", level: "advanced" },
  { id: 6, word: "fragile", meaning: "깨지기 쉬운, 연약한", example: "Please handle this fragile vase carefully.", level: "beginner" },
  { id: 7, word: "generous", meaning: "관대한, 후한", example: "He made a generous donation to the charity.", level: "beginner" },
  { id: 8, word: "humble", meaning: "겸손한", example: "Despite her success, she remained humble.", level: "beginner" },
  { id: 9, word: "ingenious", meaning: "독창적인, 영리한", example: "The engineer came up with an ingenious solution.", level: "advanced" },
  { id: 10, word: "jubilant", meaning: "기쁨에 넘친", example: "The team was jubilant after winning the championship.", level: "advanced" },
  { id: 11, word: "keen", meaning: "예리한, 열정적인", example: "She has a keen eye for detail.", level: "intermediate" },
  { id: 12, word: "lethargic", meaning: "무기력한", example: "He felt lethargic after eating a big meal.", level: "advanced" },
  { id: 13, word: "meticulous", meaning: "꼼꼼한, 세심한", example: "She is meticulous about keeping records.", level: "advanced" },
  { id: 14, word: "notorious", meaning: "악명 높은", example: "The area is notorious for its high crime rate.", level: "intermediate" },
  { id: 15, word: "optimistic", meaning: "낙관적인", example: "Try to stay optimistic even in tough times.", level: "intermediate" },
  { id: 16, word: "persistent", meaning: "끈질긴, 지속적인", example: "Her persistent efforts finally paid off.", level: "intermediate" },
  { id: 17, word: "quaint", meaning: "고풍스러운, 특이한", example: "We stayed in a quaint little village inn.", level: "advanced" },
  { id: 18, word: "resilient", meaning: "회복력 있는", example: "Children are often resilient in difficult situations.", level: "intermediate" },
  { id: 19, word: "sincere", meaning: "진심 어린", example: "Please accept my sincere apologies.", level: "beginner" },
  { id: 20, word: "tenacious", meaning: "끈기 있는", example: "Her tenacious spirit helped her overcome all obstacles.", level: "advanced" },
  { id: 21, word: "unique", meaning: "독특한, 유일한", example: "Everyone has a unique set of fingerprints.", level: "beginner" },
  { id: 22, word: "vivid", meaning: "생생한, 선명한", example: "She has vivid memories of her childhood.", level: "intermediate" },
  { id: 23, word: "wary", meaning: "경계하는, 조심하는", example: "Be wary of strangers online.", level: "intermediate" },
  { id: 24, word: "exquisite", meaning: "정교한, 아름다운", example: "The jeweler crafted an exquisite necklace.", level: "advanced" },
  { id: 25, word: "yearning", meaning: "갈망, 그리움", example: "She felt a deep yearning for her homeland.", level: "advanced" },
  { id: 26, word: "ambitious", meaning: "야심찬", example: "He is an ambitious young entrepreneur.", level: "intermediate" },
  { id: 27, word: "brief", meaning: "간단한, 짧은", example: "Please give a brief summary of the report.", level: "beginner" },
  { id: 28, word: "clumsy", meaning: "서툰, 어색한", example: "He is clumsy and often drops things.", level: "beginner" },
  { id: 29, word: "daunting", meaning: "벅찬, 위압적인", example: "The task seemed daunting at first.", level: "intermediate" },
  { id: 30, word: "eager", meaning: "열망하는, 간절한", example: "She was eager to start her new job.", level: "beginner" },
];
